; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Povilas-Jurgulis
AppVersion=3.0
WizardStyle=modern
DefaultDirName={commonpf64}\VU\Povilas-Jurgulis
DefaultGroupName=Povilas-Jurgulis
UninstallDisplayIcon={app}\v3.0_uzduotis.exe
Compression=lzma2
SolidCompression=yes
OutputDir=userdocs:IDK

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Files]
Source: ".\build\v3.0_uzduotis.exe"; DestDir: "{app}"
Source: ".\build\10tukst_stud.txt"; DestDir: "{app}"
Source: ".\build\100tukst_stud.txt"; DestDir: "{app}"

[Icons]
Name: "{group}\Povilas-Jurgulis"; Filename: "{app}\v3.0_uzduotis.exe"
Name: {commondesktop}\Povilas-Jurgulis; Filename: {app}\v3.0_uzduotis.exe; Tasks: desktopicon