var searchData=
[
  ['į_20du_20naujus_0',['Optimizuoju skirstymą su std::copy_if ir std::partition_copy skaidant bendrą konteinerį į du naujus.',['../md__r_e_a_d_m_e.html#autotoc_md57',1,'']]],
  ['į_20du_20naujus_20failus_20ir_20visos_20programos_20veikimo_20laiką_1',['į du naujus failus ir visos programos veikimo laiką',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.']]],
  ['į_20du_20naujus_20to_20paties_20tipo_20konteinerius_3a_20kietiakiai_20ir_20nuskriaustukai_20techniškai_201_20strategija_2',['Testuoju, kai bendrą studentų konteinerį skaidau į du naujus to paties tipo konteinerius: &quot;kietiakiai&quot; ir &quot;nuskriaustukai&quot;. Techniškai 1 strategija.',['../md__r_e_a_d_m_e.html#autotoc_md36',1,'']]],
  ['į_20du_20skirtingus_20failus_3',['ir jie išvesti į du skirtingus failus.',['../md__r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['į_20dvi_20grupes_20kategorijas_20naujų_20konteinerių_20su_20skirtingais_20studentais_20kūrimas_4',['&quot;Skirstymas&quot; reiškia studentų skirstymo į dvi grupes/kategorijas (naujų konteinerių su skirtingais studentais kūrimas).',['../md__r_e_a_d_m_e.html#autotoc_md38',1,'']]],
  ['į_20dvi_20grupes_20laiką_20su_20skirtingais_20konteineriais_5',['į dvi grupes laiką su skirtingais konteineriais',['../md__r_e_a_d_m_e.html#autotoc_md40',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md41',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md42',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md43',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md44',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.']]],
  ['į_20dvi_20grupes_20laiką_20su_20skirtingais_20konteineriais_20kuriant_20tik_20nuskriaustukai_6',['į dvi grupes laiką su skirtingais konteineriais kuriant tik nuskriaustukai',['../md__r_e_a_d_m_e.html#autotoc_md50',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md51',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md52',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md53',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md54',1,'5) Testuosiu 10 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.']]],
  ['į_20dvi_20grupes_20vector_20konteineris_7',['tačiau greičiausiai nuskaito ir skirsto į dvi grupes vector konteineris.',['../md__r_e_a_d_m_e.html#autotoc_md46',1,'']]],
  ['į_20dvi_20grupes_20vietoje_20aš_20iš_20tikro_20panaudojau_203_20strategijos_20std_3a_3astable_5fpartition_20nes_20kitaip_20man_20neišėjo_8',['Antros strategijos studentų skirstymo į dvi grupes vietoje aš iš tikro panaudojau 3 strategijos std::stable_partition, nes kitaip man neišėjo.',['../md__r_e_a_d_m_e.html#autotoc_md55',1,'']]],
  ['į_20dvi_20naujas_20grupes_20laiką_20su_20skirtingais_20konteineriais_203_20strategija_9',['į dvi naujas grupes laiką su skirtingais konteineriais 3 strategija',['../md__r_e_a_d_m_e.html#autotoc_md58',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md59',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md60',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md61',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md62',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).']]],
  ['į_20skirtingus_20header_20ar_20cpp_20files_20pridėtas_20minimalus_20išimčių_20valdymas_10',['į skirtingus header ar .cpp files. Pridėtas minimalus išimčių valdymas.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['įdiegti_11',['Kaip įdiegti',['../md__r_e_a_d_m_e.html#autotoc_md64',1,'']]]
];
