var searchData=
[
  ['failų_20generavimo_20funkcija_20surūšiuoti_20studentai_20pagal_20dvi_20kategorijas_0',['Sukurta failų generavimo funkcija, surūšiuoti studentai pagal dvi kategorijas',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]],
  ['failo_20ir_20kad_20naudotojas_20galėtų_20pasirinkti_1',['Padaryta, kad duomenis eitų gauti iš tekstinio failo ir kad naudotojas galėtų pasirinkti,',['../md__r_e_a_d_m_e.html#autotoc_md8',1,'']]],
  ['failo_20nuskaitymo_20rūšiavimo_20išvedimo_20į_20du_20naujus_20failus_20ir_20visos_20programos_20veikimo_20laiką_2',['failo nuskaitymo rūšiavimo išvedimo į du naujus failus ir visos programos veikimo laiką',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.']]],
  ['failo_20nuskaitymo_20rūšiavimo_20skirstymo_20į_20dvi_20grupes_20laiką_20su_20skirtingais_20konteineriais_3',['failo nuskaitymo rūšiavimo skirstymo į dvi grupes laiką su skirtingais konteineriais',['../md__r_e_a_d_m_e.html#autotoc_md40',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md41',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md42',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md43',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md44',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.']]],
  ['failo_20nuskaitymo_20rūšiavimo_20skirstymo_20į_20dvi_20grupes_20laiką_20su_20skirtingais_20konteineriais_20kuriant_20tik_20nuskriaustukai_4',['failo nuskaitymo rūšiavimo skirstymo į dvi grupes laiką su skirtingais konteineriais kuriant tik nuskriaustukai',['../md__r_e_a_d_m_e.html#autotoc_md50',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md51',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md52',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md53',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md54',1,'5) Testuosiu 10 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.']]],
  ['failo_20nuskaitymo_20rūšiavimo_20skirstymo_20į_20dvi_20naujas_20grupes_20laiką_20su_20skirtingais_20konteineriais_203_20strategija_5',['failo nuskaitymo rūšiavimo skirstymo į dvi naujas grupes laiką su skirtingais konteineriais 3 strategija',['../md__r_e_a_d_m_e.html#autotoc_md58',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md59',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md60',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md61',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md62',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).']]],
  ['failo_20sukūrimo_20ir_20uždarymo_20laiką_6',['failo sukūrimo ir uždarymo laiką',['../md__r_e_a_d_m_e.html#autotoc_md23',1,'1) Testuosiu 1 tūkstančio studentų failo sukūrimo ir uždarymo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md24',1,'2) Testuosiu 10 tūkstančių studentų failo sukūrimo ir uždarymo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md25',1,'3) Testuosiu 100 tūkstančių studentų failo sukūrimo ir uždarymo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md26',1,'4) Testuosiu 1 milijono studentų failo sukūrimo ir uždarymo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md27',1,'5) Testuosiu 10 milijonų studentų failo sukūrimo ir uždarymo laiką.']]],
  ['failus_7',['ir jie išvesti į du skirtingus failus.',['../md__r_e_a_d_m_e.html#autotoc_md16',1,'']]],
  ['failus_20greitį_8',['pagal ką rūšiuoti. Taip pat reikėjo ištestuoti skirtingo dydžio failus (greitį).',['../md__r_e_a_d_m_e.html#autotoc_md9',1,'']]],
  ['failus_20ir_20visos_20programos_20veikimo_20laiką_9',['failus ir visos programos veikimo laiką',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.']]],
  ['file_5fgen_2ecpp_10',['file_gen.cpp',['../file__gen_8cpp.html',1,'']]],
  ['file_5fgeneravimas_11',['file_generavimas',['../deklaracijos_8h.html#aa41a2a3320ceabdfdf2ed80e2d19a59a',1,'file_generavimas(int &amp;n):&#160;file_gen.cpp'],['../file__gen_8cpp.html#aaf5e8ec15628d9405d9b345565dabfc0',1,'file_generavimas(int &amp;irasai):&#160;file_gen.cpp']]],
  ['file_5fskaitymas_12',['file_skaitymas',['../deklaracijos_8h.html#a61fef53fd0c6b361a552bfd15d69249e',1,'file_skaitymas(int &amp;vard_size, int &amp;pav_size, Pasirinkimas p, Studentas st, vector&lt; Studentas &gt; &amp;studentai, vector&lt; string &gt; vardai, vector&lt; string &gt; pavardes, time_point&lt; high_resolution_clock &gt; &amp;start, int *max_vardas_size, int *max_pavarde_size):&#160;file_skaitymas.cpp'],['../file__skaitymas_8cpp.html#a61fef53fd0c6b361a552bfd15d69249e',1,'file_skaitymas(int &amp;vard_size, int &amp;pav_size, Pasirinkimas p, Studentas st, vector&lt; Studentas &gt; &amp;studentai, vector&lt; string &gt; vardai, vector&lt; string &gt; pavardes, time_point&lt; high_resolution_clock &gt; &amp;start, int *max_vardas_size, int *max_pavarde_size):&#160;file_skaitymas.cpp']]],
  ['file_5fskaitymas_2ecpp_13',['file_skaitymas.cpp',['../file__skaitymas_8cpp.html',1,'']]],
  ['files_20pridėtas_20minimalus_20išimčių_20valdymas_14',['į skirtingus header ar .cpp files. Pridėtas minimalus išimčių valdymas.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['flag_15',['flag',['../md__r_e_a_d_m_e.html#autotoc_md73',1,'Naudosiu -O3 flag.'],['../md__r_e_a_d_m_e.html#autotoc_md84',1,'Naudosiu -O3 flag.']]],
  ['funkcijų_20ir_20duomenų_20tipų_20perkėlti_16',['Kur tikslinga programoje pradėta naudoti struktūras, daug funkcijų ir duomenų tipų perkėlti',['../md__r_e_a_d_m_e.html#autotoc_md11',1,'']]],
  ['funkcija_20surūšiuoti_20studentai_20pagal_20dvi_20kategorijas_17',['Sukurta failų generavimo funkcija, surūšiuoti studentai pagal dvi kategorijas',['../md__r_e_a_d_m_e.html#autotoc_md14',1,'']]]
];
