var searchData=
[
  ['3_20iterator_20insert_20const_5fiterator_20pos_20const_20t_20value_20_3a_0',['3. iterator insert(const_iterator pos, const T&amp; value) :',['../md__r_e_a_d_m_e.html#autotoc_md94',1,'']]],
  ['3_20strategiją_1',['Kadangi jau padariau pirmą (1) strategiją praeitame testavime, tai dabar testuosiu antrą (2) ir trečią (3) strategiją.',['../md__r_e_a_d_m_e.html#autotoc_md48',1,'']]],
  ['3_20strategija_2',['3 strategija',['../md__r_e_a_d_m_e.html#autotoc_md58',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md59',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md60',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md61',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md62',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).']]],
  ['3_20strategija_20lėtesnė_20nei_202_20ir_201_20strategija_3',['Taigi matome, kad 3 strategija lėtesnė nei 2 ir 1 strategija.',['../md__r_e_a_d_m_e.html#autotoc_md63',1,'']]],
  ['3_20strategijos_20std_3a_3astable_5fpartition_20nes_20kitaip_20man_20neišėjo_4',['Antros strategijos studentų skirstymo į dvi grupes vietoje aš iš tikro panaudojau 3 strategijos std::stable_partition, nes kitaip man neišėjo.',['../md__r_e_a_d_m_e.html#autotoc_md55',1,'']]],
  ['3_20strategijos_20tyrimas_5',['3 strategijos tyrimas',['../md__r_e_a_d_m_e.html#autotoc_md56',1,'']]],
  ['3_20testuosiu_20100_20tūkstančių_20studentų_20failo_20nuskaitymo_20rūšiavimo_20išvedimo_20į_20du_20naujus_20failus_20ir_20visos_20programos_20veikimo_20laiką_6',['3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.',['../md__r_e_a_d_m_e.html#autotoc_md31',1,'']]],
  ['3_20testuosiu_20100_20tūkstančių_20studentų_20failo_20nuskaitymo_20rūšiavimo_20skirstymo_20į_20dvi_20grupes_20laiką_20su_20skirtingais_20konteineriais_7',['3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.',['../md__r_e_a_d_m_e.html#autotoc_md42',1,'']]],
  ['3_20testuosiu_20100_20tūkstančių_20studentų_20failo_20nuskaitymo_20rūšiavimo_20skirstymo_20į_20dvi_20grupes_20laiką_20su_20skirtingais_20konteineriais_20kuriant_20tik_20nuskriaustukai_8',['3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.',['../md__r_e_a_d_m_e.html#autotoc_md52',1,'']]],
  ['3_20testuosiu_20100_20tūkstančių_20studentų_20failo_20nuskaitymo_20rūšiavimo_20skirstymo_20į_20dvi_20naujas_20grupes_20laiką_20su_20skirtingais_20konteineriais_203_20strategija_9',['3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).',['../md__r_e_a_d_m_e.html#autotoc_md60',1,'']]],
  ['3_20testuosiu_20100_20tūkstančių_20studentų_20failo_20sukūrimo_20ir_20uždarymo_20laiką_10',['3) Testuosiu 100 tūkstančių studentų failo sukūrimo ir uždarymo laiką.',['../md__r_e_a_d_m_e.html#autotoc_md25',1,'']]],
  ['3_3a_11',['v0.3:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]]
];
