var searchData=
[
  ['lėtesnė_20nei_202_20ir_201_20strategija_0',['Taigi matome, kad 3 strategija lėtesnė nei 2 ir 1 strategija.',['../md__r_e_a_d_m_e.html#autotoc_md63',1,'']]],
  ['lėtesni_20nei_20be_20bet_20galima_20sakyti_20beveik_20vienodi_1',['Taigi matome, kad testai su operatorių perdengimu buvo vos lėtesni, nei be, bet galima sakyti beveik vienodi.',['../md__r_e_a_d_m_e.html#autotoc_md79',1,'']]],
  ['lėtesni_20nei_20v1_202_20ir_20be_20operatorių_20perdengimo_2',['Taigi matome, kad v1.5 testai buvo lėtesni nei v1.2 ir be operatorių perdengimo.',['../md__r_e_a_d_m_e.html#autotoc_md88',1,'']]],
  ['laiką_3',['laiką',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md23',1,'1) Testuosiu 1 tūkstančio studentų failo sukūrimo ir uždarymo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md24',1,'2) Testuosiu 10 tūkstančių studentų failo sukūrimo ir uždarymo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md25',1,'3) Testuosiu 100 tūkstančių studentų failo sukūrimo ir uždarymo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md26',1,'4) Testuosiu 1 milijono studentų failo sukūrimo ir uždarymo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md27',1,'5) Testuosiu 10 milijonų studentų failo sukūrimo ir uždarymo laiką.']]],
  ['laiką_20su_20skirtingais_20konteineriais_4',['laiką su skirtingais konteineriais',['../md__r_e_a_d_m_e.html#autotoc_md40',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md41',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md42',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md43',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.'],['../md__r_e_a_d_m_e.html#autotoc_md44',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais.']]],
  ['laiką_20su_20skirtingais_20konteineriais_203_20strategija_5',['laiką su skirtingais konteineriais 3 strategija',['../md__r_e_a_d_m_e.html#autotoc_md58',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md59',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md60',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md61',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).'],['../md__r_e_a_d_m_e.html#autotoc_md62',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi naujas grupes laiką su skirtingais konteineriais (3 strategija).']]],
  ['laiką_20su_20skirtingais_20konteineriais_20kuriant_20tik_20nuskriaustukai_6',['laiką su skirtingais konteineriais kuriant tik nuskriaustukai',['../md__r_e_a_d_m_e.html#autotoc_md50',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md51',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md52',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md53',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.'],['../md__r_e_a_d_m_e.html#autotoc_md54',1,'5) Testuosiu 10 milijono studentų failo nuskaitymo, rūšiavimo, skirstymo į dvi grupes laiką su skirtingais konteineriais, kuriant tik &quot;nuskriaustukai&quot;.']]],
  ['laikai_20ištestuoti_20priskaitant_20vektorius_7',['Konteinerių testavimas (sukurtos list ir deque programos ir visų laikai ištestuoti priskaitant vektorius).',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['leidžia_20pasirinkti_20ar_20naudoti_20perdengtus_20operatorius_20ar_20ne_3a_8',['Ši kodo vieta leidžia pasirinkti, ar naudoti perdengtus operatorius, ar ne:',['../md__r_e_a_d_m_e.html#autotoc_md75',1,'']]],
  ['list_20ir_20deque_20programos_20ir_20visų_20laikai_20ištestuoti_20priskaitant_20vektorius_9',['Konteinerių testavimas (sukurtos list ir deque programos ir visų laikai ištestuoti priskaitant vektorius).',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['list_20konteineris_10',['Taigi, iš konteinerių testavimo matome, kad greičiausiai rūšiuoja (su sort) list konteineris,',['../md__r_e_a_d_m_e.html#autotoc_md45',1,'']]],
  ['logiką_11',['Programa išliko veiksni naudojant v1.2 logiką.',['../md__r_e_a_d_m_e.html#autotoc_md82',1,'']]]
];
