var searchData=
[
  ['v_20pradinė_3a_0',['v.pradinė:',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['v0_201_3a_1',['v0.1:',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['v0_202_3a_2',['v0.2:',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['v0_203_3a_3',['v0.3:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['v0_204_20tyrimai_4',['v0.4 Tyrimai',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['v0_204_3a_5',['v0.4:',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['v1_200_20strategijų_20tyrimai_3a_6',['v1.0 Strategijų tyrimai:',['../md__r_e_a_d_m_e.html#autotoc_md47',1,'']]],
  ['v1_200_20tyrimai_20konteinerių_20testavimas_7',['v1.0 Tyrimai (Konteinerių testavimas)',['../md__r_e_a_d_m_e.html#autotoc_md34',1,'']]],
  ['v1_200_3a_8',['v1.0:',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['v1_202_20greičio_20tyrimas_20su_201_20milijonu_20ir_2010_20milijonų_20studentų_3a_9',['v1.2 greičio tyrimas su 1 milijonu ir 10 milijonų studentų:',['../md__r_e_a_d_m_e.html#autotoc_md76',1,'']]],
  ['v1_202_20ir_20be_20operatorių_20perdengimo_10',['Taigi matome, kad v1.5 testai buvo lėtesni nei v1.2 ir be operatorių perdengimo.',['../md__r_e_a_d_m_e.html#autotoc_md88',1,'']]],
  ['v1_202_20logiką_11',['Programa išliko veiksni naudojant v1.2 logiką.',['../md__r_e_a_d_m_e.html#autotoc_md82',1,'']]],
  ['v1_202_20tyrimai_20greitis_20su_20perdengtais_20operatoriais_20ir_20be_12',['v1.2 Tyrimai (greitis su perdengtais operatoriais ir be)',['../md__r_e_a_d_m_e.html#autotoc_md70',1,'']]],
  ['v1_205_20greičio_20tyrimas_20su_201_20milijonu_20ir_2010_20milijonų_20studentų_3a_13',['v1.5 greičio tyrimas su 1 milijonu ir 10 milijonų studentų:',['../md__r_e_a_d_m_e.html#autotoc_md85',1,'']]],
  ['v1_205_20operatorių_20perdengimu_20testas_3a_14',['v1 5 operatorių perdengimu testas:',['../md__r_e_a_d_m_e.html#autotoc_md86',1,'Paskutinis 1 milijono studentų su v1.5 operatorių perdengimu testas:'],['../md__r_e_a_d_m_e.html#autotoc_md87',1,'Paskutinis 10 milijonų studentų su v1.5 operatorių perdengimu testas:']]],
  ['v1_205_20testai_20buvo_20lėtesni_20nei_20v1_202_20ir_20be_20operatorių_20perdengimo_15',['Taigi matome, kad v1.5 testai buvo lėtesni nei v1.2 ir be operatorių perdengimo.',['../md__r_e_a_d_m_e.html#autotoc_md88',1,'']]],
  ['v1_205_20tyrimai_16',['v1.5 Tyrimai',['../md__r_e_a_d_m_e.html#autotoc_md80',1,'']]],
  ['valdymas_17',['į skirtingus header ar .cpp files. Pridėtas minimalus išimčių valdymas.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['vard_5fsize_18',['vard_size',['../deklaracijos_8h.html#aa3901edaa93f3f84f994ee45741f5682',1,'vard_size:&#160;patikrinimai.cpp'],['../patikrinimai_8cpp.html#aa3901edaa93f3f84f994ee45741f5682',1,'vard_size:&#160;patikrinimai.cpp']]],
  ['vardai_19',['vardai',['../deklaracijos_8h.html#aaba84d8a6cab4a6f1e8e6376f6078c34',1,'vardai:&#160;patikrinimai.cpp'],['../patikrinimai_8cpp.html#aaba84d8a6cab4a6f1e8e6376f6078c34',1,'vardai:&#160;patikrinimai.cpp']]],
  ['vardas_20',['vardas',['../class_zmogus.html#a4d456bf4fea70f08e0b26517576cfbc0',1,'Zmogus']]],
  ['vartotojas_20galėtų_20pasirinkti_20sugeneruoti_20duomenis_21',['su C masyvu ir vektoriais. Dar padaryta, kad vartotojas galėtų pasirinkti sugeneruoti duomenis.',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['vector_20konteineris_22',['tačiau greičiausiai nuskaito ir skirsto į dvi grupes vector konteineris.',['../md__r_e_a_d_m_e.html#autotoc_md46',1,'']]],
  ['veikimo_20greičio_20su_20o1_20testavimas_23',['Programos veikimo greičio su -O1 testavimas',['../md__r_e_a_d_m_e.html#autotoc_md66',1,'']]],
  ['veikimo_20greičio_20su_20o2_20testavimas_24',['Programos veikimo greičio su -O2 testavimas',['../md__r_e_a_d_m_e.html#autotoc_md67',1,'']]],
  ['veikimo_20greičio_20su_20o3_20testavimas_25',['Programos veikimo greičio su -O3 testavimas',['../md__r_e_a_d_m_e.html#autotoc_md68',1,'']]],
  ['veikimo_20greičio_20spartos_20analizė_26',['Atlikta programos veikimo greičio (spartos) analizė.',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]],
  ['veikimo_20laiką_27',['veikimo laiką',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.']]],
  ['veiksni_20naudojant_20v1_202_20logiką_28',['Programa išliko veiksni naudojant v1.2 logiką.',['../md__r_e_a_d_m_e.html#autotoc_md82',1,'']]],
  ['veiktų_20nežinant_20kiek_20bus_20namų_20darbų_20ar_20studentų_20ir_20realizuota_29',['Padaryta, kad programa veiktų, nežinant kiek bus namų darbų ar studentų ir realizuota',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['vektoriais_20dar_20padaryta_20kad_20vartotojas_20galėtų_20pasirinkti_20sugeneruoti_20duomenis_30',['su C masyvu ir vektoriais. Dar padaryta, kad vartotojas galėtų pasirinkti sugeneruoti duomenis.',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['vektorius_31',['Konteinerių testavimas (sukurtos list ir deque programos ir visų laikai ištestuoti priskaitant vektorius).',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['versijų_20aprašymai_3a_32',['Versijų aprašymai:',['../md__r_e_a_d_m_e.html',1,'']]],
  ['vid_5far_5fmed_33',['vid_ar_med',['../class_pasirinkimas.html#a5fcf03accf0d3ee8827678468c694089',1,'Pasirinkimas']]],
  ['vidurkiu_20arba_20mediana_20taip_20pat_20ir_20duomenų_20išvedimas_34',['su vidurkiu arba mediana. Taip pat ir duomenų išvedimas.',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['vienodi_35',['Taigi matome, kad testai su operatorių perdengimu buvo vos lėtesni, nei be, bet galima sakyti beveik vienodi.',['../md__r_e_a_d_m_e.html#autotoc_md79',1,'']]],
  ['vieta_20leidžia_20pasirinkti_20ar_20naudoti_20perdengtus_20operatorius_20ar_20ne_3a_36',['Ši kodo vieta leidžia pasirinkti, ar naudoti perdengtus operatorius, ar ne:',['../md__r_e_a_d_m_e.html#autotoc_md75',1,'']]],
  ['vietoje_20aš_20iš_20tikro_20panaudojau_203_20strategijos_20std_3a_3astable_5fpartition_20nes_20kitaip_20man_20neišėjo_37',['Antros strategijos studentų skirstymo į dvi grupes vietoje aš iš tikro panaudojau 3 strategijos std::stable_partition, nes kitaip man neišėjo.',['../md__r_e_a_d_m_e.html#autotoc_md55',1,'']]],
  ['visų_20laikai_20ištestuoti_20priskaitant_20vektorius_38',['Konteinerių testavimas (sukurtos list ir deque programos ir visų laikai ištestuoti priskaitant vektorius).',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['visada_39',['Taigi matome, kad struktūros testai buvo greitesni ir -O3 buvo greičiausias beveik visada.',['../md__r_e_a_d_m_e.html#autotoc_md69',1,'']]],
  ['visos_20programos_20veikimo_20laiką_40',['visos programos veikimo laiką',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.']]],
  ['vos_20lėtesni_20nei_20be_20bet_20galima_20sakyti_20beveik_20vienodi_41',['Taigi matome, kad testai su operatorių perdengimu buvo vos lėtesni, nei be, bet galima sakyti beveik vienodi.',['../md__r_e_a_d_m_e.html#autotoc_md79',1,'']]]
];
