var searchData=
[
  ['v_20pradinė_3a_0',['v.pradinė:',['../md__r_e_a_d_m_e.html#autotoc_md1',1,'']]],
  ['v0_201_3a_1',['v0.1:',['../md__r_e_a_d_m_e.html#autotoc_md4',1,'']]],
  ['v0_202_3a_2',['v0.2:',['../md__r_e_a_d_m_e.html#autotoc_md7',1,'']]],
  ['v0_203_3a_3',['v0.3:',['../md__r_e_a_d_m_e.html#autotoc_md10',1,'']]],
  ['v0_204_20tyrimai_4',['v0.4 Tyrimai',['../md__r_e_a_d_m_e.html#autotoc_md21',1,'']]],
  ['v0_204_3a_5',['v0.4:',['../md__r_e_a_d_m_e.html#autotoc_md13',1,'']]],
  ['v1_200_20strategijų_20tyrimai_3a_6',['v1.0 Strategijų tyrimai:',['../md__r_e_a_d_m_e.html#autotoc_md47',1,'']]],
  ['v1_200_20tyrimai_20konteinerių_20testavimas_7',['v1.0 Tyrimai (Konteinerių testavimas)',['../md__r_e_a_d_m_e.html#autotoc_md34',1,'']]],
  ['v1_200_3a_8',['v1.0:',['../md__r_e_a_d_m_e.html#autotoc_md18',1,'']]],
  ['v1_202_20greičio_20tyrimas_20su_201_20milijonu_20ir_2010_20milijonų_20studentų_3a_9',['v1.2 greičio tyrimas su 1 milijonu ir 10 milijonų studentų:',['../md__r_e_a_d_m_e.html#autotoc_md76',1,'']]],
  ['v1_202_20ir_20be_20operatorių_20perdengimo_10',['Taigi matome, kad v1.5 testai buvo lėtesni nei v1.2 ir be operatorių perdengimo.',['../md__r_e_a_d_m_e.html#autotoc_md88',1,'']]],
  ['v1_202_20logiką_11',['Programa išliko veiksni naudojant v1.2 logiką.',['../md__r_e_a_d_m_e.html#autotoc_md82',1,'']]],
  ['v1_202_20tyrimai_20greitis_20su_20perdengtais_20operatoriais_20ir_20be_12',['v1.2 Tyrimai (greitis su perdengtais operatoriais ir be)',['../md__r_e_a_d_m_e.html#autotoc_md70',1,'']]],
  ['v1_205_20greičio_20tyrimas_20su_201_20milijonu_20ir_2010_20milijonų_20studentų_3a_13',['v1.5 greičio tyrimas su 1 milijonu ir 10 milijonų studentų:',['../md__r_e_a_d_m_e.html#autotoc_md85',1,'']]],
  ['v1_205_20operatorių_20perdengimu_20testas_3a_14',['v1 5 operatorių perdengimu testas:',['../md__r_e_a_d_m_e.html#autotoc_md86',1,'Paskutinis 1 milijono studentų su v1.5 operatorių perdengimu testas:'],['../md__r_e_a_d_m_e.html#autotoc_md87',1,'Paskutinis 10 milijonų studentų su v1.5 operatorių perdengimu testas:']]],
  ['v1_205_20testai_20buvo_20lėtesni_20nei_20v1_202_20ir_20be_20operatorių_20perdengimo_15',['Taigi matome, kad v1.5 testai buvo lėtesni nei v1.2 ir be operatorių perdengimo.',['../md__r_e_a_d_m_e.html#autotoc_md88',1,'']]],
  ['v1_205_20tyrimai_16',['v1.5 Tyrimai',['../md__r_e_a_d_m_e.html#autotoc_md80',1,'']]],
  ['v3_200_20vektoriaus_20kūrimas_20ir_20testai_17',['v3.0 Vektoriaus kūrimas ir testai',['../md__r_e_a_d_m_e.html#autotoc_md89',1,'']]],
  ['valdymas_18',['į skirtingus header ar .cpp files. Pridėtas minimalus išimčių valdymas.',['../md__r_e_a_d_m_e.html#autotoc_md12',1,'']]],
  ['value_20_3a_19',['3. iterator insert(const_iterator pos, const T&amp; value) :',['../md__r_e_a_d_m_e.html#autotoc_md94',1,'']]],
  ['vartotojas_20galėtų_20pasirinkti_20sugeneruoti_20duomenis_20',['su C masyvu ir vektoriais. Dar padaryta, kad vartotojas galėtų pasirinkti sugeneruoti duomenis.',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['vector_21',['Vector',['../class_vector.html',1,'']]],
  ['vector_20h_20funkcijų_20aprašymas_3a_22',['5 Skirtingų Vector.h funkcijų aprašymas:',['../md__r_e_a_d_m_e.html#autotoc_md91',1,'']]],
  ['vector_20h_20vs_20std_3a_3avector_23',['Efektyvumo/spartos analizė - Vector.h VS std::vector',['../md__r_e_a_d_m_e.html#autotoc_md97',1,'']]],
  ['vector_20ir_20std_3a_3avector_20atminties_20perskirstymai_20užpildant_20100000000_20elementų_3a_24',['Kiek kartų įvyksta konteinerių (Vector ir std::vector) atminties perskirstymai užpildant 100000000 elementų:',['../md__r_e_a_d_m_e.html#autotoc_md104',1,'']]],
  ['vector_20konteineris_25',['tačiau greičiausiai nuskaito ir skirsto į dvi grupes Vector konteineris.',['../md__r_e_a_d_m_e.html#autotoc_md46',1,'']]],
  ['vector_3c_20int_20_3e_26',['Vector&lt; int &gt;',['../class_vector.html',1,'']]],
  ['veikimo_20greičio_20su_20o1_20testavimas_27',['Programos veikimo greičio su -O1 testavimas',['../md__r_e_a_d_m_e.html#autotoc_md66',1,'']]],
  ['veikimo_20greičio_20su_20o2_20testavimas_28',['Programos veikimo greičio su -O2 testavimas',['../md__r_e_a_d_m_e.html#autotoc_md67',1,'']]],
  ['veikimo_20greičio_20su_20o3_20testavimas_29',['Programos veikimo greičio su -O3 testavimas',['../md__r_e_a_d_m_e.html#autotoc_md68',1,'']]],
  ['veikimo_20greičio_20spartos_20analizė_30',['Atlikta programos veikimo greičio (spartos) analizė.',['../md__r_e_a_d_m_e.html#autotoc_md17',1,'']]],
  ['veikimo_20laiką_31',['veikimo laiką',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.']]],
  ['veiksni_20naudojant_20v1_202_20logiką_32',['Programa išliko veiksni naudojant v1.2 logiką.',['../md__r_e_a_d_m_e.html#autotoc_md82',1,'']]],
  ['veiktų_20nežinant_20kiek_20bus_20namų_20darbų_20ar_20studentų_20ir_20realizuota_33',['Padaryta, kad programa veiktų, nežinant kiek bus namų darbų ar studentų ir realizuota',['../md__r_e_a_d_m_e.html#autotoc_md5',1,'']]],
  ['vektorių_34',['Reikia kompiliuoti su C++20, nes naudojau construct_at() ir destroy_at() metodus, kad realizuoti vektorių.',['../md__r_e_a_d_m_e.html#autotoc_md90',1,'']]],
  ['vektoriais_20dar_20padaryta_20kad_20vartotojas_20galėtų_20pasirinkti_20sugeneruoti_20duomenis_35',['su C masyvu ir vektoriais. Dar padaryta, kad vartotojas galėtų pasirinkti sugeneruoti duomenis.',['../md__r_e_a_d_m_e.html#autotoc_md6',1,'']]],
  ['vektoriaus_20kūrimas_20ir_20testai_36',['v3.0 Vektoriaus kūrimas ir testai',['../md__r_e_a_d_m_e.html#autotoc_md89',1,'']]],
  ['vektorius_37',['Konteinerių testavimas (sukurtos list ir deque programos ir visų laikai ištestuoti priskaitant vektorius).',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['versijų_20aprašymai_3a_38',['Versijų aprašymai:',['../md__r_e_a_d_m_e.html',1,'']]],
  ['vidurkiu_20arba_20mediana_20taip_20pat_20ir_20duomenų_20išvedimas_39',['su vidurkiu arba mediana. Taip pat ir duomenų išvedimas.',['../md__r_e_a_d_m_e.html#autotoc_md3',1,'']]],
  ['vienodi_40',['Taigi matome, kad testai su operatorių perdengimu buvo vos lėtesni, nei be, bet galima sakyti beveik vienodi.',['../md__r_e_a_d_m_e.html#autotoc_md79',1,'']]],
  ['vieta_20leidžia_20pasirinkti_20ar_20naudoti_20perdengtus_20operatorius_20ar_20ne_3a_41',['Ši kodo vieta leidžia pasirinkti, ar naudoti perdengtus operatorius, ar ne:',['../md__r_e_a_d_m_e.html#autotoc_md75',1,'']]],
  ['vietoje_20aš_20iš_20tikro_20panaudojau_203_20strategijos_20std_3a_3astable_5fpartition_20nes_20kitaip_20man_20neišėjo_42',['Antros strategijos studentų skirstymo į dvi grupes vietoje aš iš tikro panaudojau 3 strategijos std::stable_partition, nes kitaip man neišėjo.',['../md__r_e_a_d_m_e.html#autotoc_md55',1,'']]],
  ['visų_20laikai_20ištestuoti_20priskaitant_20vektorius_43',['Konteinerių testavimas (sukurtos list ir deque programos ir visų laikai ištestuoti priskaitant vektorius).',['../md__r_e_a_d_m_e.html#autotoc_md19',1,'']]],
  ['visada_44',['Taigi matome, kad struktūros testai buvo greitesni ir -O3 buvo greičiausias beveik visada.',['../md__r_e_a_d_m_e.html#autotoc_md69',1,'']]],
  ['visos_20programos_20veikimo_20laiką_45',['visos programos veikimo laiką',['../md__r_e_a_d_m_e.html#autotoc_md29',1,'1) Testuosiu 1 tūkstančio studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md30',1,'2) Testuosiu 10 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md31',1,'3) Testuosiu 100 tūkstančių studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md32',1,'4) Testuosiu 1 milijono studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.'],['../md__r_e_a_d_m_e.html#autotoc_md33',1,'5) Testuosiu 10 milijonų studentų failo nuskaitymo, rūšiavimo, išvedimo į du naujus failus ir visos programos veikimo laiką.']]],
  ['void_20append_5frange_20r_20rg_20_3a_46',['5. template &lt;R&gt; void append_range(R&amp;&amp; rg) :',['../md__r_e_a_d_m_e.html#autotoc_md96',1,'']]],
  ['void_20assign_5frange_20r_20rg_20_3a_47',['4.  template &lt;R&gt; void assign_range(R&amp;&amp; rg) :',['../md__r_e_a_d_m_e.html#autotoc_md95',1,'']]],
  ['void_20reserve_20std_3a_3asize_5ft_20new_5fcap_20_3a_48',['1. void reserve(std::size_t new_cap) :',['../md__r_e_a_d_m_e.html#autotoc_md92',1,'']]],
  ['void_20resize_20std_3a_3asize_5ft_20new_5fsize_20_3a_49',['2. void resize(std::size_t new_size) :',['../md__r_e_a_d_m_e.html#autotoc_md93',1,'']]],
  ['vos_20lėtesni_20nei_20be_20bet_20galima_20sakyti_20beveik_20vienodi_50',['Taigi matome, kad testai su operatorių perdengimu buvo vos lėtesni, nei be, bet galima sakyti beveik vienodi.',['../md__r_e_a_d_m_e.html#autotoc_md79',1,'']]],
  ['vs_20std_3a_3avector_51',['Efektyvumo/spartos analizė - Vector.h VS std::vector',['../md__r_e_a_d_m_e.html#autotoc_md97',1,'']]]
];
